package co.stellarskys.stella.features.secrets.utils

import co.stellarskys.stella.Stella
import co.stellarskys.stella.annotations.Module
import com.google.gson.GsonBuilder
import net.minecraft.core.BlockPos
import java.awt.Color
import java.io.File

@Module
object RouteRegistry {
    private val ROUTES_FILE = File("config/stella/routes.json")
    private val gson = GsonBuilder().disableHtmlEscaping().create()
    private var routeFile: RouteFile = RouteFile()

    init {
        load()
    }

    fun load() {
        if (!ROUTES_FILE.exists()) {
            Stella.LOGGER.info("RouteRegistry: routes.json not found, creating new file")
            save()
            return
        }

        runCatching {
            val json = ROUTES_FILE.readText()
            routeFile = gson.fromJson(json, RouteFile::class.java)
            Stella.LOGGER.info("RouteRegistry: Loaded routes.json")
        }.onFailure {
            Stella.LOGGER.error("RouteRegistry: Failed to load routes.json — ${it.message}")
        }
    }

    fun save() {
        runCatching {
            val sb = StringBuilder()

            // Opening brace
            sb.append("{\n")

            // Header fields
            sb.append("    \"#name\": \"${routeFile.`#name`}\",\n")
            sb.append("    \"#origin\": \"${routeFile.`#origin`}\",\n")
            sb.append("    \"Version\": \"${routeFile.Version}\",\n\n")

            // Each room on its own line
            val entries = routeFile.routes.entries.toList()
            entries.forEachIndexed { index, (room, data) ->
                sb.append("    \"").append(room).append("\":")
                sb.append(gson.toJson(data.steps)) // compact JSON array

                // Add comma except for last entry
                if (index != entries.lastIndex) sb.append(",")
                sb.append("\n")
            }

            // Closing brace
            sb.append("}")

            ROUTES_FILE.parentFile.mkdirs()
            ROUTES_FILE.writeText(sb.toString())

            Stella.LOGGER.info("RouteRegistry: Saved routes.json")
        }.onFailure {
            Stella.LOGGER.error("RouteRegistry: Failed to save routes.json — ${it.message}")
        }
    }

    fun saveRoute(roomName: String, steps: List<StepData>) {
        val serializable = RouteData(steps.map { it.toSerializable() })
        routeFile.routes[roomName] = serializable
        save()
    }

    fun getRoute(roomName: String): RouteData? =
        routeFile.routes[roomName]

    fun getAll(): Map<String, RouteData> =
        routeFile.routes

    data class RouteFile(
        val `#name`: String = "Default secret routes",
        val `#origin`: String = "generated by Stella",
        val Version: String = "1.0",
        val routes: MutableMap<String, RouteData> = mutableMapOf()
    )

    data class RouteData(
        val steps: List<StepDataSerializable>
    )

    data class StepDataSerializable(
        val waypoints: List<WaypointDataSerializable>,
        val line: List<List<Int>> // [[x, y, z], ...]
    )

    data class WaypointDataSerializable(
        val pos: List<Int>,       // [x, y, z]
        val type: String,
        val name: String?,
        val color: List<Int>?     // [r, g, b]
    )

    fun BlockPos.toList() = listOf(x, y, z)

    fun Color.toList() = listOf(red, green, blue)

    fun StepData.toSerializable() = StepDataSerializable(
        waypoints = waypoints.map { it.toSerializable() },
        line = line.map { it.toList() }
    )

    fun WaypointData.toSerializable() = WaypointDataSerializable(
        pos = pos.toList(),
        type = type.name,
        name = name,
        color = color?.toList()
    )
}
