name: Run Gradle Build

on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    outputs:
      commit-number: ${{ steps.commit-count.outputs.commit-number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Calculate commit number
        id: commit-count
        run: echo "commit-number=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew clean buildAndCollect
      - name: Process built JARs
        run: |
          mkdir -p build/processed
          find . -type f -name "*.jar" -path "*/build/libs/*" | while read -r jar; do
            if [[ "$jar" == *"stella-ksp"* ]]; then
              echo "Skipping KSP internal jar: $jar"
              continue
            fi

            if [[ ! "$jar" == *"-sources"* ]] && [[ ! "$jar" == *"-dev"* ]] && [[ ! "$jar" == *"-refmap"* ]]; then
              filename=$(basename "$jar")
              raw_version=${filename#stella-}
              clean_version=${raw_version%.jar}
              if [[ "$raw_version" == "$filename" ]]; then
                 echo "Skipping non-mod jar: $filename"
                 continue
              fi

              new_name="stella-${clean_version}-fabric-nightly-${{ steps.commit-count.outputs.commit-number }}.jar"
              echo "Processing: $new_name"
              cp "$jar" "build/processed/$new_name"
            fi
          done
      - name: Upload built mod JARs
        uses: actions/upload-artifact@v4.3.0
        with:
          name: stella-fabric-nightly-${{ steps.commit-count.outputs.commit-number }}
          path: build/processed/*.jar
